PID: 19188
honu.cs.washington.edu
Job started at Wed Aug 21 00:28:20 PDT 2019
[RESOURCES] There are too many total processes running: 44!
Running patch plausibility analysis under Java-7 on the patch generated by GenProg for Bugs.jar::Commons-Math-faf99727::0
patch_plausibility.py script started at Wed Aug 21 00:28:47 PDT 2019
Switched to branch 'bugs-dot-jar_MATH-1096_faf99727'
Reinitialized existing Git repository in /tmp/GenProg_Bugs.jar_Commons-Math_faf99727/.git/
Checking patch java/org/apache/commons/math3/geometry/enclosing/WelzlEncloser.java...
error: java/org/apache/commons/math3/geometry/enclosing/WelzlEncloser.java: No such file or directory
Checking patch java/org/apache/commons/math3/exception/util/ExceptionContext.java...
error: java/org/apache/commons/math3/exception/util/ExceptionContext.java: No such file or directory
`patch` has failed!
Traceback (most recent call last):
  File "/scratch/rjust/critical_review_of_repair_them_all_data/plausibility/patch_plausibility.py", line 161, in <module>
    die("`patch` has failed!\n")
  File "/scratch/rjust/critical_review_of_repair_them_all_data/plausibility/patch_plausibility.py", line 104, in die
    utils.die(msg=msg, checkout_dir=CHECKOUT_DIR)
  File "/scratch/rjust/critical_review_of_repair_them_all_data/java_7_vs_java_8/utils.py", line 35, in die
    sys.exit(1)
SystemExit: 1
Checkout Bugs.jar_Commons-Math_faf99727
Apply patch ...
patch_plausibility.py has failed!
