---
BugID: FLINK-2412
Summary: Race leading to IndexOutOfBoundsException when querying for buffer while
  releasing SpillablePartition
Description: "When running a code as simple as: \n\n{noformat}\n\t\tExecutionEnvironment
  env = ExecutionEnvironment.getExecutionEnvironment();\n\n\t\tDataSet<Edge<String,
  NullValue>> edges = getEdgesDataSet(env);\n\t\tGraph<String, NullValue, NullValue>
  graph = Graph.fromDataSet(edges, env);\n\n\t\tDataSet<Tuple2<String, Long>> degrees
  = graph.getDegrees();\ndegrees.writeAsCsv(outputPath, \"\\n\", \" \");\n\t\t\tenv.execute();\n\non
  the Freindster data set: https://snap.stanford.edu/data/com-Friendster.html; on
  30 Wally nodes\n \nI get the following exception:\njava.lang.Exception: The data
  preparation for task 'CoGroup (CoGroup at inDegrees(Graph.java:701))' , caused an
  error: Error obtaining the sorted input: Thread 'SortMerger Reading Thread' terminated
  due to an exception: Fatal error at remote task manager 'wally028.cit.tu-berlin.de/130.149.249.38:53730'.\n\tat
  org.apache.flink.runtime.operators.RegularPactTask.run(RegularPactTask.java:471)\n\tat
  org.apache.flink.runtime.operators.RegularPactTask.invoke(RegularPactTask.java:362)\n\tat
  org.apache.flink.runtime.taskmanager.Task.run(Task.java:559)\n\tat java.lang.Thread.run(Thread.java:722)\nCaused
  by: java.lang.RuntimeException: Error obtaining the sorted input: Thread 'SortMerger
  Reading Thread' terminated due to an exception: Fatal error at remote task manager
  'wally028.cit.tu-berlin.de/130.149.249.38:53730'.\n\tat org.apache.flink.runtime.operators.sort.UnilateralSortMerger.getIterator(UnilateralSortMerger.java:607)\n\tat
  org.apache.flink.runtime.operators.RegularPactTask.getInput(RegularPactTask.java:1145)\n\tat
  org.apache.flink.runtime.operators.CoGroupDriver.prepare(CoGroupDriver.java:98)\n\tat
  org.apache.flink.runtime.operators.RegularPactTask.run(RegularPactTask.java:466)\n\t...
  3 more\nCaused by: java.io.IOException: Thread 'SortMerger Reading Thread' terminated
  due to an exception: Fatal error at remote task manager 'wally028.cit.tu-berlin.de/130.149.249.38:53730'.\n\tat
  org.apache.flink.runtime.operators.sort.UnilateralSortMerger$ThreadBase.run(UnilateralSortMerger.java:784)\nCaused
  by: org.apache.flink.runtime.io.network.netty.exception.RemoteTransportException:
  Fatal error at remote task manager 'wally028.cit.tu-berlin.de/130.149.249.38:53730'.\n\tat
  org.apache.flink.runtime.io.network.netty.PartitionRequestClientHandler.decodeMsg(PartitionRequestClientHandler.java:227)\n\tat
  org.apache.flink.runtime.io.network.netty.PartitionRequestClientHandler.channelRead(PartitionRequestClientHandler.java:162)\n\tat
  io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)\n\tat
  io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324)\n\tat
  io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)\n\tat
  io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)\n\tat
  io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324)\n\tat
  io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:242)\n\tat
  io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)\n\tat
  io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324)\n\tat
  io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:847)\n\tat
  io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)\n\tat
  io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)\n\tat
  io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)\n\tat
  io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)\n\tat
  io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)\n\tat
  java.lang.Thread.run(Thread.java:722)\nCaused by: java.io.IOException: Index: 133,
  Size: 0\n\n{noformat}\n\nCode works fine for the twitter data set, for instance,
  which is bigger in size, but contains less vertices.  \n\n"
