PID: 15247
honu.cs.washington.edu
Job started at Wed Aug 21 13:23:10 PDT 2019
Running patch plausibility analysis under Java-8 on the patch generated by jGenProg for Bugs.jar::Commons-Math-cc4ab51e::0
patch_plausibility.py script started at Wed Aug 21 13:23:10 PDT 2019
Switched to branch 'bugs-dot-jar_MATH-1136_cc4ab51e'
Picked up JAVA_TOOL_OPTIONS: -XX:CICompilerCount=2 -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2  
Reinitialized existing Git repository in /tmp/jGenProg_Bugs.jar_Commons-Math_cc4ab51e/.git/
Checking patch src/main/java/b/src/main/java/org/apache/commons/math3/distribution/SaddlePointExpansion.java...
error: src/main/java/b/src/main/java/org/apache/commons/math3/distribution/SaddlePointExpansion.java: No such file or directory
`patch` has failed!
Traceback (most recent call last):
  File "/scratch/rjust/critical_review_of_repair_them_all_data/plausibility/patch_plausibility.py", line 161, in <module>
    die("`patch` has failed!\n")
  File "/scratch/rjust/critical_review_of_repair_them_all_data/plausibility/patch_plausibility.py", line 104, in die
    utils.die(msg=msg, checkout_dir=CHECKOUT_DIR)
  File "/scratch/rjust/critical_review_of_repair_them_all_data/java_7_vs_java_8/utils.py", line 35, in die
    sys.exit(1)
SystemExit: 1
Checkout Bugs.jar_Commons-Math_cc4ab51e
Apply patch ...
Get module information
patch_plausibility.py has failed!
