PID: 28586
honu.cs.washington.edu
Job started at Wed Aug 21 00:31:36 PDT 2019
[RESOURCES] There are too many total processes running: 41!
[RESOURCES] There are too many total processes running: 55!
[RESOURCES] There are too many total processes running: 46!
Running patch plausibility analysis under Java-7 on the patch generated by Kali for Bugs.jar::Jackrabbit-Oak-c83755c3::0
patch_plausibility.py script started at Wed Aug 21 00:32:43 PDT 2019
Switched to branch 'bugs-dot-jar_OAK-3396_c83755c3'
Reinitialized existing Git repository in /tmp/Kali_Bugs.jar_Jackrabbit-Oak_c83755c3/.git/
Checking patch main/java/org/apache/jackrabbit/oak/security/authentication/ldap/impl/LdapIdentityProvider.java...
error: main/java/org/apache/jackrabbit/oak/security/authentication/ldap/impl/LdapIdentityProvider.java: No such file or directory
`patch` has failed!
Traceback (most recent call last):
  File "/scratch/rjust/critical_review_of_repair_them_all_data/plausibility/patch_plausibility.py", line 161, in <module>
    die("`patch` has failed!\n")
  File "/scratch/rjust/critical_review_of_repair_them_all_data/plausibility/patch_plausibility.py", line 104, in die
    utils.die(msg=msg, checkout_dir=CHECKOUT_DIR)
  File "/scratch/rjust/critical_review_of_repair_them_all_data/java_7_vs_java_8/utils.py", line 35, in die
    sys.exit(1)
SystemExit: 1
Checkout Bugs.jar_Jackrabbit-Oak_c83755c3
Apply patch ...
patch_plausibility.py has failed!
