PID: 16610
bam.cs.washington.edu
Job started at Thu Mar 12 03:09:48 PDT 2020
Running checkout, compile, and test under Java-7 on Bears::Activiti-activiti-cloud-app-service-459060444-459062447. Excluding broken tests? false. Running on the buggy version? true.
compile_and_test.py script started at Thu Mar 12 03:09:49 PDT 2020
Previous HEAD position was 6616eba1b Changes in the tests This commit is based on the source code from the following commit: http://github.com/2018swecapstone/h2ms/commit/ef42b1078bd7f6699a5c47d01627360e03fc1705 The mentioned commit triggered the following Travis build: http://travis-ci.org/2018swecapstone/h2ms/builds/363627522.
Switched to branch 'Activiti-activiti-cloud-app-service-459060444-459062447'
Note: checking out 'dd7e6c9ae9da9ffd481c75043aa7571bfd07b3e5'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at dd7e6c9ae Bug commit from Activiti/activiti-cloud-app-service This commit is based on the source code from the following commit: http://github.com/Activiti/activiti-cloud-app-service/commit/09c98b115e0b663b5008d0a237b6b940c6819064 The mentioned commit triggered the following Travis build: http://travis-ci.org/Activiti/activiti-cloud-app-service/builds/459060444.
compile has failed!
Traceback (most recent call last):
  File "/bam/scratch/jmcampos/RTA/repair_them_all_framework/data/benchmarks-reproducibility/checkout_and_compile_and_metadata_and_test.py", line 121, in <module>
    die()
  File "/bam/scratch/jmcampos/RTA/repair_them_all_framework/data/benchmarks-reproducibility/checkout_and_compile_and_metadata_and_test.py", line 95, in die
    utils.die(msg=msg, checkout_dir=CHECKOUT_DIR)
  File "/scratch/jmcampos/RTA/repair_them_all_framework/script/utils.py", line 35, in die
    sys.exit(1)
SystemExit: 1
Checkout Bears_Activiti-activiti-cloud-app-service_459060444-459062447
Compile Bears_Activiti-activiti-cloud-app-service_459060444-459062447
/bam/scratch/jmcampos/RTA/repair_them_all_framework/data/benchmarks-reproducibility/checkout_and_compile_and_metadata_and_test.py has failed!
