PID: 95419
tricycle.cs.washington.edu
Job started at Thu Mar 12 09:47:54 PDT 2020
Running checkout, compile, and test under Java-7 on Bears::Activiti-activiti-cloud-app-service-459060444-459062447. Excluding broken tests? false. Running on the buggy version? false.
compile_and_test.py script started at Thu Mar 12 09:47:54 PDT 2020
Previous HEAD position was 661afa804 Human patch from INRIA/spoon This commit is based on the source code from the following commit: http://github.com/INRIA/spoon/commit/3041002595d0497cca31f9c5fd65a706abec9117 The mentioned commit triggered the following Travis build: http://travis-ci.org/INRIA/spoon/builds/249603843.
Switched to branch 'Activiti-activiti-cloud-app-service-459060444-459062447'
Note: checking out '092164cd23332fdf11c481ae15fd3fdf723b2b86'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 092164cd2 Human patch from Activiti/activiti-cloud-app-service This commit is based on the source code from the following commit: http://github.com/Activiti/activiti-cloud-app-service/commit/d66c4337ff021d552cec2c045ea025bb9b27f631 The mentioned commit triggered the following Travis build: http://travis-ci.org/Activiti/activiti-cloud-app-service/builds/459062447.
compile has failed!
Traceback (most recent call last):
  File "/scratch/jmcampos/RTA/repair_them_all_framework/data/benchmarks-reproducibility/checkout_and_compile_and_metadata_and_test.py", line 121, in <module>
    die()
  File "/scratch/jmcampos/RTA/repair_them_all_framework/data/benchmarks-reproducibility/checkout_and_compile_and_metadata_and_test.py", line 95, in die
    utils.die(msg=msg, checkout_dir=CHECKOUT_DIR)
  File "/scratch/jmcampos/RTA/repair_them_all_framework/script/utils.py", line 35, in die
    sys.exit(1)
SystemExit: 1
Checkout Bears_Activiti-activiti-cloud-app-service_459060444-459062447
Compile Bears_Activiti-activiti-cloud-app-service_459060444-459062447
/scratch/jmcampos/RTA/repair_them_all_framework/data/benchmarks-reproducibility/checkout_and_compile_and_metadata_and_test.py has failed!
